spring.config.activate.on-profile: dev

spring:
  config:
    import:
      - application-secret-aws.yml
      - application-secret-datasource.yml
      - application-secret-jwt.yml
logging:
  config: classpath:logback-spring.xml

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB