spring.config.activate.on-profile: prod

spring:
  config:
    import:
      - application-secret-aws.yml
      - application-secret-datasource.yml
      - application-secret-jwt.yml
      - application-secret-redis.yml
logging:
  config: classpath:logback-spring.xml